# Generated by Django 3.0.10 on 2020-10-31 14:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assign_tasks', '0002_auto_20201031_1734'),
        ('tasks', '0003_auto_20201031_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код')),
                ('lang', models.CharField(choices=[('python', 'Python'), ('c', 'C')], max_length=6, verbose_name='Язык')),
                ('status', models.CharField(choices=[('check', 'Проверка'), ('ok', 'OK'), ('error', 'Ошибка')], default='check', max_length=5, verbose_name='Статус')),
                ('sent_dt', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 14, 34, 33, 805197, tzinfo=utc), verbose_name='Время отправки')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assign_tasks.AssignTask')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['-sent_dt'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('check', 'Проверка'), ('ok', 'OK'), ('error', 'Ошибка')], default='check', max_length=5, verbose_name='Статус')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_dispatching.Dispatch')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.InOutTest')),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
                'ordering': ['test__order'],
            },
        ),
    ]
