# Generated by Django 3.0.10 on 2020-11-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_dispatching', '0002_auto_20201031_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('check', 'CHECK'), ('error', 'ERROR')], max_length=5, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('to', 'TO'), ('wa', 'WA'), ('mo', 'MO'), ('re', 'RE'), ('ce', 'CE')], max_length=15, null=True, verbose_name='Статус'),
        ),
    ]
