# Generated by Django 3.0.10 on 2020-11-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_dispatching', '0004_auto_20201101_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='score',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Кол-во баллов'),
        ),
    ]
