# Generated by Django 3.0.10 on 2020-11-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201101_0852'),
        ('task_dispatching', '0005_dispatch_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Test'),
        ),
    ]
