version: '3'

volumes:
  postgres_data: {}

services:
  django: &django
    build:
      context: .
      dockerfile: .docker/django/Dockerfile
    depends_on:
      - postgres
      - mailhog
      - rabbitmq
    volumes:
      - .:/app:z
    env_file:
      - .docker/django/dotenv
      - .docker/postgres/dotenv
      - .docker/mailhog/dotenv
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: library/postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    env_file:
      - .docker/postgres/dotenv

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  rabbitmq:
    image: library/rabbitmq:3.8.9-alpine

  celeryworker:
    <<: *django
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    ports: []
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app:z
    command: /start-celeryworker

  celerybeat:
    <<: *django
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
