# Generated by Django 3.0.10 on 2020-10-30 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Название')),
                ('legend', models.TextField(verbose_name='Легенда')),
                ('condition', models.TextField(verbose_name='Условие')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_in', models.TextField(verbose_name='Вход')),
                ('data_out', models.TextField(verbose_name='Выход')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
            },
        ),
        migrations.CreateModel(
            name='InOutTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_in', models.TextField(verbose_name='Вход')),
                ('data_out', models.TextField(verbose_name='Выход')),
                ('order', models.PositiveSmallIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Тест типа "Ввод-Вывод"',
                'verbose_name_plural': 'Тесты типа "Ввод-Вывод"',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CheckerTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('python', 'Python'), ('C', 'c')], max_length=6, verbose_name='Язык')),
                ('code', models.TextField(verbose_name='Код')),
                ('order', models.PositiveSmallIntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task')),
            ],
            options={
                'verbose_name': 'Тест типа "Чекер"',
                'verbose_name_plural': 'Тест типа "Чекер"',
                'ordering': ['order'],
            },
        ),
    ]
