# Generated by Django 3.0.10 on 2020-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkertest',
            name='lang',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C')], max_length=6, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='inouttest',
            name='data_in',
            field=models.TextField(blank=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='inouttest',
            name='data_out',
            field=models.TextField(blank=True, verbose_name='Выход'),
        ),
        migrations.AlterField(
            model_name='tasksample',
            name='data_in',
            field=models.TextField(blank=True, verbose_name='Вход'),
        ),
        migrations.AlterField(
            model_name='tasksample',
            name='data_out',
            field=models.TextField(blank=True, verbose_name='Выход'),
        ),
    ]
