# Generated by Django 3.0.10 on 2020-10-31 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201031_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkertest',
            options={'verbose_name': 'Тест типа "Чекер"', 'verbose_name_plural': 'Тест типа "Чекер"'},
        ),
        migrations.AlterModelOptions(
            name='inouttest',
            options={'verbose_name': 'Тест типа "Ввод-Вывод"', 'verbose_name_plural': 'Тесты типа "Ввод-Вывод"'},
        ),
        migrations.AlterField(
            model_name='checkertest',
            name='order',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inouttest',
            name='order',
            field=models.PositiveSmallIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='tasksample',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_set', to='tasks.Task'),
        ),
    ]
