# Generated by Django 3.0.10 on 2020-11-01 05:50

from django.db import migrations


def delete_all_tests(apps, schema_editor):
    InOutTest = apps.get_model('tasks', 'InOutTest')
    CheckerTest = apps.get_model('tasks', 'CheckerTest')
    for test in InOutTest.objects.all():
        test.delete()
    for test in CheckerTest.objects.all():
        test.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201031_1115'),
    ]

    operations = [
        migrations.RunPython(delete_all_tests, reverse_code=delete_all_tests),
    ]
