# Generated by Django 3.0.10 on 2020-11-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201101_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkertest',
            name='lang',
            field=models.CharField(choices=[('python', 'Python'), ('c', 'C'), ('javascript', 'JavaScript'), ('pascal', 'Pascal')], max_length=10, verbose_name='Язык'),
        ),
    ]
