# Generated by Django 3.0.10 on 2020-10-31 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assigntask',
            options={'ordering': ['-assign_dt'], 'verbose_name': 'Назначенная задача', 'verbose_name_plural': 'Назначенные задачи'},
        ),
    ]
