# Generated by Django 3.0.10 on 2020-11-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign_tasks', '0002_auto_20201031_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigntask',
            name='status',
        ),
    ]
